apiVersion: batch/v1
kind: CronJob
metadata:
  name: fetch-latest-status-job
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      parallelism : 2
      template:
        spec:
          containers:
            - name: sample
              image: krpsanthoshkumar/sample-project-0.0.1
              imagePullPolicy: Always
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30